import { defineConfig } from "eslint/config";
import eslintJs from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintReact from "@eslint-react/eslint-plugin";
import globals from "globals";

export default defineConfig([
    {
        files: ["**/*.{ts,mts,cts,tsx}"],
        ignores: ["**/build/**"],
        extends: [
            eslintJs.configs.recommended,
            tseslint.configs.recommendedTypeChecked,
            tseslint.configs.stylisticTypeChecked,
            eslintReact.configs["recommended-type-checked"],
        ],
        languageOptions: {
            globals: globals.browser,
            parser: tseslint.parser,
            parserOptions: {
                projectService: true,
            },
        },
        settings: {
            "react-x": {
                compilationMode: "infer",
            },
        },
        rules: {
            // @jetbrains/eslint-config/base
            "getter-return": "error",
            "no-cond-assign": ["error", "except-parens"],
            "no-console": "off", // changed
            "no-constant-condition": "error",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-dupe-args": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-empty-character-class": "error",
            "no-empty": "error",
            "no-ex-assign": "error",
            "no-extra-boolean-cast": "error",
            "no-func-assign": "error",
            "no-inner-declarations": "error",
            "no-invalid-regexp": "error",
            "no-irregular-whitespace": "error",
            "no-negated-in-lhs": "error",
            "no-obj-calls": "error",
            "no-regex-spaces": "error",
            "no-sparse-arrays": "error",
            "no-unexpected-multiline": "error",
            "no-unreachable": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
            "accessor-pairs": "error",
            "array-callback-return": "error",
            "block-scoped-var": "error",
            complexity: ["warn", 20],
            "consistent-return": "error",
            "default-case": "error",
            "dot-notation": "error",
            eqeqeq: ["error", "allow-null"],
            "guard-for-in": "error",
            "no-alert": "error",
            "no-caller": "error",
            "no-div-regex": "error",
            "no-else-return": "off",
            "no-empty-pattern": "error",
            "no-eq-null": "off",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-fallthrough": "error",
            "no-implicit-coercion": "off",
            "no-implied-eval": "error",
            "no-invalid-this": "off",
            "no-iterator": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-loop-func": "error",
            "no-magic-numbers": "off",
            "no-multi-str": "error",
            "no-native-reassign": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-new": "error",
            "no-octal-escape": "error",
            "no-octal": "error",
            "no-param-reassign": "error",
            "no-process-env": "off",
            "no-proto": "error",
            "no-redeclare": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-throw-literal": "error",
            "no-unused-expressions": "error",
            "no-useless-call": "error",
            "no-useless-concat": "error",
            "no-void": ["error", { allowAsStatement: true }],
            "no-warning-comments": "off",
            "no-with": "error",
            radix: "error",
            "vars-on-top": "error",
            yoda: "error",
            strict: ["error", "never"],
            "init-declarations": "off",
            "no-catch-shadow": "error",
            "no-delete-var": "error",
            "no-label-var": "error",
            "no-shadow-restricted-names": "error",
            "no-shadow": "off",
            "no-undef-init": "error",
            "no-undefined": "off",
            "no-use-before-define": ["error", "nofunc"],

            // @jetbrains/eslint-config/style
            camelcase: "error",
            "consistent-this": ["error", "this"],
            "func-names": "error",
            "func-style": ["error", "declaration", { allowArrowFunctions: true }],
            "id-length": "off",
            "id-match": "error",
            "max-nested-callbacks": "off",
            "new-cap": "error",
            "no-array-constructor": "error",
            "no-continue": "off",
            "no-inline-comments": "off",
            "no-lonely-if": "error",
            "no-negated-condition": "off",
            "no-nested-ternary": "error",
            "no-new-object": "error",
            "no-restricted-syntax": "error",
            "no-spaced-func": "error",
            "no-ternary": "off",
            "no-underscore-dangle": "off",
            "no-unneeded-ternary": "error",
            "one-var": ["error", "never"],
            "operator-assignment": ["error", "always"],
            "sort-vars": "off",

            // @jetbrains/eslint-config/react
            "@eslint-react/dom-no-missing-button-type": "error",
            "@eslint-react/no-missing-component-display-name": "error",
            "@eslint-react/no-missing-key": "error",
            "@eslint-react/no-duplicate-key": "error",
            "@eslint-react/no-implicit-key": "error",
            "@eslint-react/jsx-no-comment-textnodes": "error",
            "@eslint-react/dom-no-unsafe-target-blank": "error",
            "@eslint-react/jsx-no-useless-fragment": "error",
            "@eslint-react/no-access-state-in-setstate": "error",
            "@eslint-react/no-array-index-key": "error",
            "@eslint-react/jsx-no-children-prop": "error",
            "@eslint-react/dom-no-dangerously-set-innerhtml": "off",
            "@eslint-react/dom-no-dangerously-set-innerhtml-with-children": "error",
            "@eslint-react/no-component-will-mount": "error",
            "@eslint-react/no-component-will-receive-props": "error",
            "@eslint-react/no-component-will-update": "error",
            "@eslint-react/no-create-ref": "error",
            "@eslint-react/no-forward-ref": "error",
            "@eslint-react/dom-no-render": "error",
            "@eslint-react/dom-no-render-return-value": "error",
            "@eslint-react/dom-no-hydrate": "error",
            "@eslint-react/dom-no-find-dom-node": "error",
            "@eslint-react/no-set-state-in-component-did-mount": "error",
            "@eslint-react/no-set-state-in-component-did-update": "error",
            "@eslint-react/no-direct-mutation-state": "error",
            "@eslint-react/dom-no-unknown-property": "error",
            "@eslint-react/dom-no-string-style-prop": "error",
            "@eslint-react/dom-no-void-elements-with-children": "error",
            "@eslint-react/exhaustive-deps": "error",
            "@eslint-react/rules-of-hooks": "error",

            // Personal
            "preserve-caught-error": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/prefer-nullish-coalescing": [
                "error",
                { ignorePrimitives: { string: true } },
            ],
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    ignoreRestSiblings: true,
                    varsIgnorePattern: "^_",
                    args: "all",
                    argsIgnorePattern: "^_",
                    destructuredArrayIgnorePattern: "^_",
                },
            ],
            "@typescript-eslint/no-deprecated": "warn",
            "@eslint-react/use-state": ["error", { enforceSetterName: false }],
            "@eslint-react/naming-convention-ref-name": "off",
            "@eslint-react/set-state-in-effect": "error",
            "@eslint-react/web-api-no-leaked-timeout": "error",
        },
    },
    {
        files: ["src/**/*.js"],
        ignores: ["**/build/**"],
        extends: [eslintJs.configs.recommended],
        languageOptions: {
            globals: globals.node,
            sourceType: "module",
        },
    },
]);